# Generated by Django 4.2.30 on 2026-07-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mosque', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('matches_supervised', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('chief_imam', models.CharField(max_length=100)),
                ('active_users', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100)),
                ('reported_user', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('wali_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Unverified', 'Unverified')], default='Unverified', max_length=20)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=50)),
                ('document_preview_url', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walis', to='dashboard.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nikah', 'Nikah'), ('meeting planned', 'Meeting Planned'), ('active chat', 'Active Chat'), ('closed', 'Closed')], default='active chat', max_length=20)),
                ('created_at', models.DateField()),
                ('imam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='dashboard.imam')),
                ('seeker_female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_female', to='dashboard.seeker')),
                ('seeker_male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_male', to='dashboard.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='dashboard.match')),
            ],
        ),
    ]
