# Generated by Django 4.2.30 on 2026-07-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
