# Generated by Django 4.2.30 on 2026-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seeker_email_seeker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seeker',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='seeker',
            name='children',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='contact_whatsapp',
            field=models.CharField(default='07045859388', max_length=20),
        ),
        migrations.AddField(
            model_name='seeker',
            name='currently_based_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='genotype',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='seeker',
            name='health_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seeker',
            name='islamic_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seeker',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='seeker',
            name='marriage_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='mode_of_dressing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seeker',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='open_to_polygamy',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='seeker',
            name='profile_handler',
            field=models.CharField(default='HalalPairs by UmmuBilal', max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='spouse_age_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='spouse_children',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='spouse_desired_qualities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seeker',
            name='spouse_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='seeker',
            name='spouse_marital_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seeker',
            name='tribe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seeker',
            name='willing_to_relocate',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
