# Generated by Django 4.2.30 on 2026-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_seeker_about_me_seeker_age_seeker_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
