# Generated by Django 4.2.30 on 2026-08-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_seeker_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
