# Generated by Django 4.2.30 on 2026-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_seeker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wali',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wali',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
